### ISSUE TITLE
Uncaught Carbon_Fields\Exception\Incorrect_Syntax_Exception

### ISSUE THREAD

**Issue by polevaultweb** [WPUserManager/wp-user-manager#45]
```Fatal error: Uncaught Carbon_Fields\Exception\Incorrect_Syntax_Exception: Attempted to access a field before the carbon_fields_register_fields and carbon_fields_fields_registered actions have fired yet. in /var/www/CNICUST/wp-content/plugins/wp-user-manager/vendor/htmlburger/carbon-fields/core/Exception/Incorrect_Syntax_Exception.php:19 Stack trace: #0 /var/www/CNICUST/wp-content/plugins/wp-user-manager/vendor/htmlburger/carbon-fields/core/Carbon_Fields.php(217): Carbon_Fields\Exception\Incorrect_Syntax_Exception::raise('Attempted to ac...') #1 /var/www/CNICUST/wp-content/plugins/wp-user-manager/vendor/htmlburger/carbon-fields/core/Helper/Helper.php(23): Carbon_Fields\Carbon_Fields::verify_fields_registered() #2 /var/www/CNICUST/wp-content/plugins/wp-user-manager/vendor/htmlburger/carbon-fields/core/Helper/Helper.php(69): Carbon_Fields\Helper\Helper::get_field('user_meta', '', 'current_user_av...') #3 /var/www/CNICUST/wp-content/plugins/wp-user-manager/vendor/htmlburger/carbon-fields/core/Helper/Helper.php(114): Carbon_Fi in /var/www/CNICUST/wp-content/plugins/wp-user-manager/vendor/htmlburger/carbon-fields/core/Exception/Incorrect_Syntax_Exception.php on line 19```

**Comment by polevaultweb** [comment]
This happens because Fusion Builder calls the avatar URL on after_theme_setup, which we filter on using carbon fields for the avatar field. But at after_theme_setup, Carbon fields hasn't properly been loaded (init)
